### ISSUE TITLE
Load sometimes fails on Chrome and Microsoft Edge browsers

### ISSUE THREAD

**Issue by ArcadeFever** [kostasKar/logoMor#1]
First let me say thank you for making this awesome interactive site (and repo) for learning the Logo language!  But I have discovered a minor bug with Windows Chrome and Microsoft Edge browsers.  Firefox browser however, doesn't seem to have this problem.  I'm running this on a Windows 10 machine, I have not tried the same browsers on other operating systems.

FireFox
86.0.1 (64-bit)

Google Chrome is up to date
Version 89.0.4389.90 (Official Build) (64-bit)

Microsoft Edge
Version 89.0.774.54 (Official build) (64-bit)

Steps to reproduce bug on Chrome/Edge:

1. Go to https://logomor.com and load a sample logo program from your local drive.
2. Click the "Demo" button
3. Click the "Load" button and try to load the same local file (it will not load)
4. If you try to load a different filename, it will work. So it only seems to be related to the last filename locally loaded in between demo loads.

**Comment by kostasKar** [comment]
Hello ArcadeFever,

I am very glad you like this project 
Thank you for your contribution!

You are absolutely right. There is a hidded input element with a function bound to its 'onchange' event:
`<input id="inp" type='file' style="display:none;" onchange="readFile(event)" />`
That's why it doesn't seem to do anything if you select the same file as previously.  
In firefox it indeed seems to not mind about that

**Comment by kostasKar** [comment]
Fixed with commit 512c7a4d142cbdaa695f5f12b4e7f383547cf637
The value of the file input field is reset every time it is clicked, so any file triggers the onchange event even if it is the same as the lastly selected.
Applied to both source code load and to model add
